function Hd = mybandpassfilterIIR_EEG_500(Fs, Fc1, Fc2, N)
%MYBANDPASSFILTERIIR_ECG_500 Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 24-Aug-2015 16:34:26
%

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs =128;  % Sampling Frequency

% N   = 6;   % Order
% Fc1 = 2;   % First Cutoff Frequency
% Fc2 = 16;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');
% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);

% [EOF]
